from _typeshed import Incomplete
from collections.abc import Generator, MutableMapping
from typing import NamedTuple

MULTI_VALUED_JOINER: str
LENGTH_SCORE_THRES_MS: int


class SimMatchTrack(NamedTuple):
    similarity: Incomplete
    releasegroup: Incomplete
    release: Incomplete
    track: Incomplete


class SimMatchRelease(NamedTuple):
    similarity: Incomplete
    release: Incomplete


def weights_from_release_type_scores(parts, release, release_type_scores, weight_release_type: int = 1) -> None: ...


def weights_from_preferred_countries(parts, release, preferred_countries, weight) -> None: ...


def weights_from_preferred_formats(parts, release, preferred_formats, weight) -> None: ...


def trackcount_score(actual, expected): ...


class Metadata(MutableMapping):
    multi_valued_joiner = MULTI_VALUED_JOINER
    deleted_tags: Incomplete
    length: int
    images: Incomplete
    has_common_images: bool

    def __init__(self, *args, deleted_tags=None, images=None, length=None, **kwargs) -> None: ...

    def __bool__(self) -> bool: ...

    def __len__(self) -> int: ...

    @staticmethod
    def length_score(a, b): ...

    def compare(self, other, ignored=None): ...

    def compare_to_release(self, release, weights): ...

    def compare_to_release_parts(self, release, weights): ...

    def compare_to_track(self, track, weights): ...

    def copy(self, other, copy_images: bool = True) -> None: ...

    def update(self, *args, **kwargs) -> None: ...

    def diff(self, other): ...

    def clear(self) -> None: ...

    def clear_deleted(self) -> None: ...

    @staticmethod
    def normalize_tag(name): ...

    def getall(self, name): ...

    def getraw(self, name): ...

    def get(self, key, default=None): ...

    def __getitem__(self, name): ...

    def set(self, name, values) -> None: ...

    def __setitem__(self, name, values) -> None: ...

    def __contains__(self, name) -> bool: ...

    def __delitem__(self, name) -> None: ...

    def delete(self, name) -> None: ...

    def add(self, name, value) -> None: ...

    def add_unique(self, name, value) -> None: ...

    def unset(self, name) -> None: ...

    def __iter__(self): ...

    def items(self) -> Generator[Incomplete]: ...

    def rawitems(self): ...

    def apply_func(self, func) -> None: ...

    def strip_whitespace(self) -> None: ...


class MultiMetadataProxy:
    WRITE_METHODS: Incomplete
    metadata: Incomplete
    combined_metadata: Incomplete

    def __init__(self, metadata, *readonly_metadata) -> None: ...

    def __getattr__(self, name): ...

    def __setattr__(self, name, value) -> None: ...

    def __getitem__(self, name): ...

    def __setitem__(self, name, values) -> None: ...

    def __delitem__(self, name) -> None: ...

    def __iter__(self): ...

    def __len__(self) -> int: ...

    def __contains__(self, name) -> bool: ...


def register_album_metadata_processor(function, priority=...) -> None: ...


def register_track_metadata_processor(function, priority=...) -> None: ...


def run_album_metadata_processors(album_object, metadata, release) -> None: ...


def run_track_metadata_processors(album_object, metadata, track, release=None) -> None: ...
